definitions:
  dns.DNSEntry:
    properties:
      content:
        type: string
      domain:
        type: string
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      ttl:
        type: integer
      type:
        type: string
    type: object
  dns.DNSRecord:
    properties:
      content:
        type: string
      name:
        type: string
      provider:
        type: string
      ttl:
        type: integer
      type:
        type: string
    type: object
  prxmx.Node:
    properties:
      ip:
        items:
          type: string
        type: array
      name:
        type: string
      running:
        type: boolean
      uptime:
        $ref: '#/definitions/prxmx.Uptime'
    type: object
  prxmx.Uptime:
    properties:
      days:
        type: integer
      hours:
        type: integer
      minutes:
        type: integer
      raw:
        type: integer
      seconds:
        type: integer
    type: object
info:
  contact:
    email: ipedrazas@gmail.com
    name: Ivan Pedrazas
    url: https://i2.alacasa.uk
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /dns/:zone/entries:
    get:
      consumes:
      - application/json
      parameters:
      - description: Cloud Provider
        in: query
        name: provider
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dns.DNSEntry'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: List DNS entries
  /dns/:zone/records:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dns.DNSRecord'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create a DNS record
  /dns/:zone/records/:id:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Cloud Provider
        in: query
        name: provider
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dns.DNSRecord'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Delete a DNS record
    get:
      consumes:
      - application/json
      parameters:
      - description: Cloud Provider
        in: query
        name: provider
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dns.DNSRecord'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Read a DNS record
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dns.DNSRecord'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Update a DNS record
  /dns/ip/:ip:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dns.DNSRecord'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Check if an IP is in use
  /healtz/ready:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Check if the service is ready
  /proxmox/nodes:
    get:
      consumes:
      - application/json
      description: Get cluster nodes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get cluster nodes
      tags:
      - prxmx
  /proxmox/vms:
    get:
      consumes:
      - application/json
      description: Get virtual machines
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/prxmx.Node'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get virtual machines
      tags:
      - prxmx
swagger: "2.0"
